---
title: "Mentorship"
page-layout: full
title-block-banner: true
editor: source
---

## Mentoring philosophy

Each mentee has different experience levels, working and communication styles, and professional goals. As such, I strive to mentor each student individually and cater my mentoring style to their needs.

## Current mentees

#### **Mingyuan Zhu**

**2024 - Present** \| Undergraduate student, University of California, Davis.  
Project: Fin evolution in fishes

#### **Shih-Na Liu**

**2022 - Present** \| Undergraduate student, University of California, Davis.  
Project: Body shape diversification in coral reef fishes


## Former mentees

-   **Victor de Brito (2020-2023)** - Collection Manager, Cornell University
    -  Publication: de Brito, V., R. Betancur-R, M.D. Burns, T.J. Buser, K.W. Conway, J.P. Fontenelle, M.A. Kolmann, W.T. McCraney, C.E. Thacker, D.D. Bloom. (2022). Patterns of phenotypic evolution associated with marine/freshwater transitions in fishes. *Integrative Comparative Biology* 62(2): 406-423. doi: [10.1093/icb/icac085](https://academic.oup.com/icb/article/62/2/406/6604365){target="_blank"}
-   **Lindsey DeHaan (2020-2023)** - PhD student, University of Michigan
    -    Publication: DeHaan, L.M., M.D. Burns, J.P. Egan, D.D. Bloom. (2023). Diadromy drives elevated rates of trait evolution and ecomorphological convergence in Clupeiformes (herring, shad, and anchovies). *The American Naturalist* doi: [10.1086/726894](https://www.journals.uchicago.edu/doi/abs/10.1086/726894?journalCode=an){target="_blank"}
-   **Gabriella Commisso (2020-2023)** - PhD student, University of Washington
-   **Justin Hansen (2016-2019)** - Assistant project leader, ODFW
    -   Presentations: Hansen, J. and M.D. Burns. 2016. Evolution of the axial skeleton in the fish order Characiformes. Gilbert Ichthyology Society Annual Meeting, Blue River, OR (Oral Presentation)
-   **Francisco Pickens (2013-2016)** - Research staff, OSU
    -   Publications: LaRochelle, C., F.A.T. Pickens, M.D. Burns, B.L. Sidlauskas. 2016. Long-term Isopropanol storage does not alter fish morphometrics. *Copeia* 104(2):411-420. doi: [10.1643/CG-15-303](https://doi.org/10.1643/CG-15-303){target="_blank"}
    -   Presentations: Pickens, F.A.T., Larochelle, C.R., **Burns, M.D.**, and B.L. Sidlauskas. Long-term isopropanol storage does not alter fish morphometrics. RAFWE Symposium, Oregon State University February 2016 (Oral Presentation). *Best undergraduate student talk.*
-   **Rachel Keefe (2016)** - Postdoctoral Researcher, Mount Holyoke College
-   **Marcus Chatfield, MSc (2014-2015)** - Aquatic Resource Coordinator, Oregon Dept of State Lands
    -   Publications: Burns, M.D., M. Chatfield, J.L.O. Birindelli, B.L. Sidlauskas. 2017. Systematic assessment of the *Leporinus desmotes* species complex, with a description of two new species. *Neotropical Ichthyology* 15(2): e160166. doi: [10.1590/1982-0224-20160166](https://doi.org/10.1590/1982-0224-20160166){target="_blank"}
-   **Colette LaRochelle (2013-2015)**
    -   Publications: LaRochelle, C., F.A.T. Pickens, M.D. Burns, B.L. Sidlauskas. 2016. Long-term Isopropanol storage does not alter fish morphometrics. *Copeia* 104(2):411-420. doi: [10.1643/CG-15-303](https://doi.org/10.1643/CG-15-303){target="_blank"}
